--liquibase formatted sql

--changeset deepak:20230519

CREATE TABLE customer_data (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reference_id VARCHAR(255) NOT NULL,
   name VARCHAR(255),
   phone_number VARCHAR(255) UNIQUE NOT NULL,
   session_token VARCHAR(255) NOT NULL,
   email VARCHAR(255),
   address TEXT,
   is_active BOOLEAN,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   CONSTRAINT pk_customer_data PRIMARY KEY (id)
);