--liquibase formatted sql

--changeset  deepak:20230514

CREATE TABLE login_data (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reference_id VARCHAR(255) NOT NULL,
   phone_number VARCHAR(255) NOT NULL,
   session_token VARCHAR(255),
   is_expired BOOLEAN NOT NULL,
   expiry_reason VARCHAR(255),
   app_platform VARCHAR(255) NOT NULL,
   otp VARCHAR(5),
   otp_verified BOOLEAN,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   CONSTRAINT pk_demo PRIMARY KEY (id)
);