--liquibase formatted sql

--changeset deepak:20230809

CREATE TABLE cook_data (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reference_id VARCHAR(255) NOT NULL,
   name VARCHAR(255) NOT NULL,
   phone_number VARCHAR(255) NOT NULL,
   pan_number VARCHAR(255) NOT NULL,
   vendor_id BIGINT NOT NULL,
   description VARCHAR(255),
   address TEXT,
   specialities TEXT,
   feedback TEXT,
   status VARCHAR(255),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   CONSTRAINT pk_cook_data PRIMARY KEY (id),
   CONSTRAINT fk_cook_data FOREIGN KEY (vendor_id) REFERENCES vendor_data(id)
);