--liquibase formatted sql

--changeset  mayank:20240114

CREATE TABLE auth_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    otp VARCHAR(5),
    is_validated BOOLEAN,
    validation_attempts BIGINT,
    expiration_time TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version INTEGER,
    platform VARCHAR(255),
    CONSTRAINT pk_demo PRIMARY KEY (id)
);