--liquibase formatted sql

--changeset deepak:20230724

CREATE TABLE order_history (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reference_id VARCHAR(255) NOT NULL,
   customer_reference_id VARCHAR(255) NOT NULL,
   product_id BIGINT NOT NULL,
   status VARCHAR(255) NOT NULL,
   order_count INTEGER,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   CONSTRAINT pk_order_history PRIMARY KEY (id),
   CONSTRAINT fk_order_history FOREIGN KEY (product_id) REFERENCES product_data(id)
);