--liquibase formatted sql

--changeset deepak:20230619

CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    customer_reference_id VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    phone_number VARCHAR(255) NOT NULL,
    address_first VARCHAR(255) NOT NULL,
    address_second VARCHAR(255),
    pin_code VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version INTEGER,
    CONSTRAINT pk_address_data PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ck_customer_reference_id_title ON address(customer_reference_id, title);
