--liquibase formatted sql

--changeset deepak:20230519

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    external_reference_id VARCHAR(25) NOT NULL,
    name VARCHAR(255),
    phone_number VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version INTEGER,
    CONSTRAINT pk_customer_data PRIMARY KEY (id)
);