--liquibase formatted sql

--changeset deepak:20230727

CREATE TABLE delivery_data (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reference_id VARCHAR(255) NOT NULL,
   name VARCHAR(255) NOT NULL,
   phone_number VARCHAR(255) NOT NULL,
   order_id BIGINT NOT NULL,
   total_cost DOUBLE PRECISION,
   status VARCHAR(255),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   CONSTRAINT pk_delivery_data PRIMARY KEY (id),
   CONSTRAINT fk_delivery_data FOREIGN KEY (order_id) REFERENCES order_history(id)
);