--liquibase formatted sql

--changeset deepak:20230727

CREATE TABLE delivery_data (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reference_id VARCHAR(255) NOT NULL,
   customer_reference_id VARCHAR(255) NOT NULL,
   delivery_boy_id BIGINT,
   order_id BIGINT NOT NULL,
   address_id BIGINT NOT NULL,
   coupon_id BIGINT,
   final_cost DOUBLE PRECISION,
   delivery_cost DOUBLE PRECISION,
   discount_amount DOUBLE PRECISION,
   status VARCHAR(255),
   description TEXT,
   delivery_time TIMESTAMP WITHOUT TIME ZONE,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   CONSTRAINT pk_delivery_data PRIMARY KEY (id),
   CONSTRAINT fk_delivery_data FOREIGN KEY (order_id) REFERENCES order_history(id)
);