--liquibase formatted sql

--changeset deepak:20230724

CREATE TABLE order_history (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reference_id VARCHAR(255) NOT NULL,
   customer_reference_id VARCHAR(255) NOT NULL,
   product_list TEXT,
   status VARCHAR(255) NOT NULL,
   total_cost DOUBLE PRECISION,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   version INTEGER,
   CONSTRAINT pk_order_history PRIMARY KEY (id)
);