--liquibase formatted sql

--changeset  mayank:20240115

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    customer_reference_id VARCHAR(255) NOT NULL,
    is_expired BOOLEAN,
    expiration_time TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    version INTEGER,
    platform VARCHAR(255),
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);